version: "3.7"

x-mysql-variables: &mysql_variables
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      <<: *mysql_variables
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      # used to automatically create the tables defined in the schemas folder on start-up of database
      - "./schemas:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    restart: always

  # # used if mysql is already up and running and new table schemas need to be added
  # create-tables:
  #   image: mysql:8.0
  #   command: sh -c "mysql -h database -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} < /schemas/test.sql"
  #   depends_on:
  #     - database
  #   volumes:
  #     - "./schemas:/schemas"

  upload-data:
    image: upload
    build: images/upload
    command: ["python","-u", "./upload_csv_datasets.py"]
    environment:
      <<: *mysql_variables
      DATA_FILES: places,people
    volumes:
      - ./data:/data

  query-data:
    image: query
    build: images/query
    command: ["python","-u", "./query_datasets.py"]
    environment:
      <<: *mysql_variables
    volumes:
      - ./data:/data
